### ISSUE TITLE
Kullanıcı Kaydı Alma

### ISSUE THREAD

**Issue by fatiharslann** [fatiharslann/Alisgram#41]
Giriş yapan kullanıcının bilgileri Firebase database kısmına eklenecek.
şimdilik ad-soyad, e-mail ve kullanıcı idsi olsa yeterli. Ama alınabiliyorsa yaş ve cinsiyette alınsın

**Comment by HasanKarasahin** [comment]
Kullanici bilgileri güncellenebiliyor.
